[package]
name = "delservopari"
version = "0.1.0"
edition = "2018"


[dependencies]
octocrab = "0.11"
tokio = { version = "1.6.1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
serde = { version = "1.0", features = ["derive"] }
egg-mode = "0.16"
